### ISSUE TITLE
Tracking issue for P1 blocked integration/unit tests

### ISSUE THREAD

**Issue by NotStirred** [OpenCubicChunks/CubicChunks3#24]
### ChunkMap
 - Only `cc_updateChunkScheduling` and calls from `ChunkHolder#cc_getOrScheduleFuture` are tested

### ChunkHolder
 - Only `cc_getOrScheduleFuture` is tested

### MixinMinecraftServer
- [ ] `setInitialSpawn`, only unit test, requires integration test
  - [ ] `cc_replaceChunkPosInSetInitialSpawn`
  - [ ] `cc_replaceGetWorldPositionInSetInitialSpawn`
- [ ] `prepareLevels` only unit test, requires integration test
  - [ ] `cc_replaceAddRegionTicketInPrepareLevels`
  - [ ] `cc_waitUntilCubicGenerationComplete`

### MixinLevel
- Mixins
  - [ ] `setBlock` only unit test, requires integration test
    - [ ] `cc_replaceLevelChunkInGetChunkAt`
    - [ ] `cc_replaceLevelChunkInSetBlockState`
    - [ ] `cc_replaceLevelChunkInMarkAndNotifyBlock`
  - [ ] `getBlockState` only unit test, requires integration test
    - [ ] `cc_replaceLevelChunkInGetBlockState`
    - [ ] `cc_replaceLevelChunkInGetBlockState` (overload)
  - [ ] `getBlockEntity` only unit test, requires integration test
    - [ ] `cc_replaceGetChunkAtInSetBlockEntity`
  - [ ] `getFluidState` only unit test, requires integration test
    - [ ] `cc_replaceGetChunkAtInGetFluidState`
  - [ ] `setBlockEntity` only unit test, requires integration test | might break if vanilla code is added after the cancel.
    - [ ] `cc_replaceLevelChunkInSetBlockEntity`
  - [ ] `removeBlockEntity` only unit test, requires integration test
    - [ ] `cc_replaceGetChunkAtInRemoveBlockEntity`
    - [ ] `cc_replaceLevelChunkInRemoveBlockEntity`
  - [ ] `isLoaded` only unit test, requires integration test
    - [ ] `cc_replaceHasChunkInIsLoaded`
  - [ ] `loadedAndEntityCanStandOnFace` only unit test, requires integration test
    - [ ] `cc_replaceGetChunkAtInLoadedAndEntityCanStandOnFace`
  - [ ] `blockEntityChanged` only unit test, requires integration test
    - [ ] `cc_replaceBlockEntityChanged`
  - [ ] `getCurrentDifficultyAt` only unit test, requires integration test
    - [ ] `cc_replaceGetCurrentDifficultyAt`

- CC methods
  - [ ] `LevelCube cc_getCube` only unit test, requires integration test
  - [ ] `CubeAccess cc_getCube` only unit test, requires integration test
  - [ ] `cc_getCubeAt` only unit test, requires integration test
  - [ ] `cc_hasCubeAt` no test
  - [ ] `cc_hasCubesAt` no test

### CubicChunkSource
 - [ ] None tested, missing `ServerChunkCache` and `ClientChunkCache` to test.
